# Generated by Django 3.1 on 2021-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbuy_app', '0002_auto_20210414_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rate',
            field=models.FloatField(default=0),
        ),
    ]
