# Generated by Django 3.1 on 2021-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_auto_20210414_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
